replicaCount: 1

image:
  repository: ghcr.io/sudosuops/trustcatai-monai-infer
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    nvidia.com/gpu: 1

service:
  type: ClusterIP
  port: 8080

weights:
  pvc: ""
